# Generated by Django 4.2.6 on 2023-10-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, max_length=400, null=True, verbose_name='содержание')),
                ('picture', models.ImageField(blank=True, default='place_holder.png', null=True, upload_to='', verbose_name='изображение')),
                ('view_counter', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
